/*
Entelechy HTTP API

HTTP API for Entelechy

API version: 0.5.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package entelechy

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// SessionsAPIService SessionsAPI service
type SessionsAPIService service

type ApiApiBootstrapSessionV1DefaultBanksBankIdSessionsBootstrapPostRequest struct {
	ctx context.Context
	ApiService *SessionsAPIService
	bankId string
	bootstrapRequest *BootstrapRequest
	authorization *string
}

func (r ApiApiBootstrapSessionV1DefaultBanksBankIdSessionsBootstrapPostRequest) BootstrapRequest(bootstrapRequest BootstrapRequest) ApiApiBootstrapSessionV1DefaultBanksBankIdSessionsBootstrapPostRequest {
	r.bootstrapRequest = &bootstrapRequest
	return r
}

func (r ApiApiBootstrapSessionV1DefaultBanksBankIdSessionsBootstrapPostRequest) Authorization(authorization string) ApiApiBootstrapSessionV1DefaultBanksBankIdSessionsBootstrapPostRequest {
	r.authorization = &authorization
	return r
}

func (r ApiApiBootstrapSessionV1DefaultBanksBankIdSessionsBootstrapPostRequest) Execute() (*BootstrapResponse, *http.Response, error) {
	return r.ApiService.ApiBootstrapSessionV1DefaultBanksBankIdSessionsBootstrapPostExecute(r)
}

/*
ApiBootstrapSessionV1DefaultBanksBankIdSessionsBootstrapPost SVT-CP vFinal Session Bootstrap

Bootstrap a session across models using the strict mathematical MWPMC.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param bankId
 @return ApiApiBootstrapSessionV1DefaultBanksBankIdSessionsBootstrapPostRequest
*/
func (a *SessionsAPIService) ApiBootstrapSessionV1DefaultBanksBankIdSessionsBootstrapPost(ctx context.Context, bankId string) ApiApiBootstrapSessionV1DefaultBanksBankIdSessionsBootstrapPostRequest {
	return ApiApiBootstrapSessionV1DefaultBanksBankIdSessionsBootstrapPostRequest{
		ApiService: a,
		ctx: ctx,
		bankId: bankId,
	}
}

// Execute executes the request
//  @return BootstrapResponse
func (a *SessionsAPIService) ApiBootstrapSessionV1DefaultBanksBankIdSessionsBootstrapPostExecute(r ApiApiBootstrapSessionV1DefaultBanksBankIdSessionsBootstrapPostRequest) (*BootstrapResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *BootstrapResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "SessionsAPIService.ApiBootstrapSessionV1DefaultBanksBankIdSessionsBootstrapPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/v1/default/banks/{bank_id}/sessions/bootstrap"
	localVarPath = strings.Replace(localVarPath, "{"+"bank_id"+"}", url.PathEscape(parameterValueToString(r.bankId, "bankId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.bootstrapRequest == nil {
		return localVarReturnValue, nil, reportError("bootstrapRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.authorization != nil {
		parameterAddToHeaderOrQuery(localVarHeaderParams, "authorization", r.authorization, "simple", "")
	}
	// body params
	localVarPostBody = r.bootstrapRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
