/*
Entelechy HTTP API

HTTP API for Entelechy

API version: 0.5.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package entelechy

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChatCompletionMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChatCompletionMessage{}

// ChatCompletionMessage struct for ChatCompletionMessage
type ChatCompletionMessage struct {
	Role string `json:"role"`
	Content NullableString `json:"content,omitempty"`
	Name NullableString `json:"name,omitempty"`
	ToolCalls []map[string]interface{} `json:"tool_calls,omitempty"`
	ToolCallId NullableString `json:"tool_call_id,omitempty"`
}

type _ChatCompletionMessage ChatCompletionMessage

// NewChatCompletionMessage instantiates a new ChatCompletionMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChatCompletionMessage(role string) *ChatCompletionMessage {
	this := ChatCompletionMessage{}
	this.Role = role
	return &this
}

// NewChatCompletionMessageWithDefaults instantiates a new ChatCompletionMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChatCompletionMessageWithDefaults() *ChatCompletionMessage {
	this := ChatCompletionMessage{}
	return &this
}

// GetRole returns the Role field value
func (o *ChatCompletionMessage) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *ChatCompletionMessage) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *ChatCompletionMessage) SetRole(v string) {
	o.Role = v
}

// GetContent returns the Content field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChatCompletionMessage) GetContent() string {
	if o == nil || IsNil(o.Content.Get()) {
		var ret string
		return ret
	}
	return *o.Content.Get()
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChatCompletionMessage) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Content.Get(), o.Content.IsSet()
}

// HasContent returns a boolean if a field has been set.
func (o *ChatCompletionMessage) HasContent() bool {
	if o != nil && o.Content.IsSet() {
		return true
	}

	return false
}

// SetContent gets a reference to the given NullableString and assigns it to the Content field.
func (o *ChatCompletionMessage) SetContent(v string) {
	o.Content.Set(&v)
}
// SetContentNil sets the value for Content to be an explicit nil
func (o *ChatCompletionMessage) SetContentNil() {
	o.Content.Set(nil)
}

// UnsetContent ensures that no value is present for Content, not even an explicit nil
func (o *ChatCompletionMessage) UnsetContent() {
	o.Content.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChatCompletionMessage) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChatCompletionMessage) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ChatCompletionMessage) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ChatCompletionMessage) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *ChatCompletionMessage) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ChatCompletionMessage) UnsetName() {
	o.Name.Unset()
}

// GetToolCalls returns the ToolCalls field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChatCompletionMessage) GetToolCalls() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}
	return o.ToolCalls
}

// GetToolCallsOk returns a tuple with the ToolCalls field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChatCompletionMessage) GetToolCallsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.ToolCalls) {
		return nil, false
	}
	return o.ToolCalls, true
}

// HasToolCalls returns a boolean if a field has been set.
func (o *ChatCompletionMessage) HasToolCalls() bool {
	if o != nil && !IsNil(o.ToolCalls) {
		return true
	}

	return false
}

// SetToolCalls gets a reference to the given []map[string]interface{} and assigns it to the ToolCalls field.
func (o *ChatCompletionMessage) SetToolCalls(v []map[string]interface{}) {
	o.ToolCalls = v
}

// GetToolCallId returns the ToolCallId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ChatCompletionMessage) GetToolCallId() string {
	if o == nil || IsNil(o.ToolCallId.Get()) {
		var ret string
		return ret
	}
	return *o.ToolCallId.Get()
}

// GetToolCallIdOk returns a tuple with the ToolCallId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ChatCompletionMessage) GetToolCallIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ToolCallId.Get(), o.ToolCallId.IsSet()
}

// HasToolCallId returns a boolean if a field has been set.
func (o *ChatCompletionMessage) HasToolCallId() bool {
	if o != nil && o.ToolCallId.IsSet() {
		return true
	}

	return false
}

// SetToolCallId gets a reference to the given NullableString and assigns it to the ToolCallId field.
func (o *ChatCompletionMessage) SetToolCallId(v string) {
	o.ToolCallId.Set(&v)
}
// SetToolCallIdNil sets the value for ToolCallId to be an explicit nil
func (o *ChatCompletionMessage) SetToolCallIdNil() {
	o.ToolCallId.Set(nil)
}

// UnsetToolCallId ensures that no value is present for ToolCallId, not even an explicit nil
func (o *ChatCompletionMessage) UnsetToolCallId() {
	o.ToolCallId.Unset()
}

func (o ChatCompletionMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChatCompletionMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role"] = o.Role
	if o.Content.IsSet() {
		toSerialize["content"] = o.Content.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.ToolCalls != nil {
		toSerialize["tool_calls"] = o.ToolCalls
	}
	if o.ToolCallId.IsSet() {
		toSerialize["tool_call_id"] = o.ToolCallId.Get()
	}
	return toSerialize, nil
}

func (o *ChatCompletionMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChatCompletionMessage := _ChatCompletionMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChatCompletionMessage)

	if err != nil {
		return err
	}

	*o = ChatCompletionMessage(varChatCompletionMessage)

	return err
}

type NullableChatCompletionMessage struct {
	value *ChatCompletionMessage
	isSet bool
}

func (v NullableChatCompletionMessage) Get() *ChatCompletionMessage {
	return v.value
}

func (v *NullableChatCompletionMessage) Set(val *ChatCompletionMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableChatCompletionMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableChatCompletionMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChatCompletionMessage(val *ChatCompletionMessage) *NullableChatCompletionMessage {
	return &NullableChatCompletionMessage{value: val, isSet: true}
}

func (v NullableChatCompletionMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChatCompletionMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
