/*
Entelechy HTTP API

HTTP API for Entelechy

API version: 0.5.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package entelechy

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BootstrapResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BootstrapResponse{}

// BootstrapResponse struct for BootstrapResponse
type BootstrapResponse struct {
	PolicyVector map[string]float32 `json:"policy_vector"`
	InjectedPrompt string `json:"injected_prompt"`
	MemoryContext string `json:"memory_context"`
}

type _BootstrapResponse BootstrapResponse

// NewBootstrapResponse instantiates a new BootstrapResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBootstrapResponse(policyVector map[string]float32, injectedPrompt string, memoryContext string) *BootstrapResponse {
	this := BootstrapResponse{}
	this.PolicyVector = policyVector
	this.InjectedPrompt = injectedPrompt
	this.MemoryContext = memoryContext
	return &this
}

// NewBootstrapResponseWithDefaults instantiates a new BootstrapResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBootstrapResponseWithDefaults() *BootstrapResponse {
	this := BootstrapResponse{}
	return &this
}

// GetPolicyVector returns the PolicyVector field value
func (o *BootstrapResponse) GetPolicyVector() map[string]float32 {
	if o == nil {
		var ret map[string]float32
		return ret
	}

	return o.PolicyVector
}

// GetPolicyVectorOk returns a tuple with the PolicyVector field value
// and a boolean to check if the value has been set.
func (o *BootstrapResponse) GetPolicyVectorOk() (map[string]float32, bool) {
	if o == nil {
		return map[string]float32{}, false
	}
	return o.PolicyVector, true
}

// SetPolicyVector sets field value
func (o *BootstrapResponse) SetPolicyVector(v map[string]float32) {
	o.PolicyVector = v
}

// GetInjectedPrompt returns the InjectedPrompt field value
func (o *BootstrapResponse) GetInjectedPrompt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.InjectedPrompt
}

// GetInjectedPromptOk returns a tuple with the InjectedPrompt field value
// and a boolean to check if the value has been set.
func (o *BootstrapResponse) GetInjectedPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.InjectedPrompt, true
}

// SetInjectedPrompt sets field value
func (o *BootstrapResponse) SetInjectedPrompt(v string) {
	o.InjectedPrompt = v
}

// GetMemoryContext returns the MemoryContext field value
func (o *BootstrapResponse) GetMemoryContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MemoryContext
}

// GetMemoryContextOk returns a tuple with the MemoryContext field value
// and a boolean to check if the value has been set.
func (o *BootstrapResponse) GetMemoryContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryContext, true
}

// SetMemoryContext sets field value
func (o *BootstrapResponse) SetMemoryContext(v string) {
	o.MemoryContext = v
}

func (o BootstrapResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BootstrapResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["policy_vector"] = o.PolicyVector
	toSerialize["injected_prompt"] = o.InjectedPrompt
	toSerialize["memory_context"] = o.MemoryContext
	return toSerialize, nil
}

func (o *BootstrapResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"policy_vector",
		"injected_prompt",
		"memory_context",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBootstrapResponse := _BootstrapResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBootstrapResponse)

	if err != nil {
		return err
	}

	*o = BootstrapResponse(varBootstrapResponse)

	return err
}

type NullableBootstrapResponse struct {
	value *BootstrapResponse
	isSet bool
}

func (v NullableBootstrapResponse) Get() *BootstrapResponse {
	return v.value
}

func (v *NullableBootstrapResponse) Set(val *BootstrapResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBootstrapResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBootstrapResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBootstrapResponse(val *BootstrapResponse) *NullableBootstrapResponse {
	return &NullableBootstrapResponse{value: val, isSet: true}
}

func (v NullableBootstrapResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBootstrapResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
