/*
Entelechy HTTP API

HTTP API for Entelechy

API version: 0.5.6
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package entelechy

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BootstrapRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BootstrapRequest{}

// BootstrapRequest struct for BootstrapRequest
type BootstrapRequest struct {
	// State Vector Token (e.g., CST-alpha...)
	Svt string `json:"svt"`
	// The latest user prompt or context window
	Context string `json:"context"`
}

type _BootstrapRequest BootstrapRequest

// NewBootstrapRequest instantiates a new BootstrapRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBootstrapRequest(svt string, context string) *BootstrapRequest {
	this := BootstrapRequest{}
	this.Svt = svt
	this.Context = context
	return &this
}

// NewBootstrapRequestWithDefaults instantiates a new BootstrapRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBootstrapRequestWithDefaults() *BootstrapRequest {
	this := BootstrapRequest{}
	return &this
}

// GetSvt returns the Svt field value
func (o *BootstrapRequest) GetSvt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Svt
}

// GetSvtOk returns a tuple with the Svt field value
// and a boolean to check if the value has been set.
func (o *BootstrapRequest) GetSvtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Svt, true
}

// SetSvt sets field value
func (o *BootstrapRequest) SetSvt(v string) {
	o.Svt = v
}

// GetContext returns the Context field value
func (o *BootstrapRequest) GetContext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Context
}

// GetContextOk returns a tuple with the Context field value
// and a boolean to check if the value has been set.
func (o *BootstrapRequest) GetContextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Context, true
}

// SetContext sets field value
func (o *BootstrapRequest) SetContext(v string) {
	o.Context = v
}

func (o BootstrapRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BootstrapRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["svt"] = o.Svt
	toSerialize["context"] = o.Context
	return toSerialize, nil
}

func (o *BootstrapRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"svt",
		"context",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBootstrapRequest := _BootstrapRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBootstrapRequest)

	if err != nil {
		return err
	}

	*o = BootstrapRequest(varBootstrapRequest)

	return err
}

type NullableBootstrapRequest struct {
	value *BootstrapRequest
	isSet bool
}

func (v NullableBootstrapRequest) Get() *BootstrapRequest {
	return v.value
}

func (v *NullableBootstrapRequest) Set(val *BootstrapRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBootstrapRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBootstrapRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBootstrapRequest(val *BootstrapRequest) *NullableBootstrapRequest {
	return &NullableBootstrapRequest{value: val, isSet: true}
}

func (v NullableBootstrapRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBootstrapRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
