generatorName: go
outputDir: ./
inputSpec: ../../entelechy-docs/static/openapi.json
packageName: entelechy
gitUserId: garybense
gitRepoId: entelechy/entelechy-clients/go
isGoSubmodule: true
enumClassPrefix: true
structPrefix: true
generateInterfaces: true
