# coding: utf-8

"""
    Entelechy HTTP API

    HTTP API for Entelechy

    The version of the OpenAPI document: 0.5.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BankTemplateConfig(BaseModel):
    """
    Bank configuration fields within a template manifest.  Only includes configurable (per-bank) fields. Credential fields (API keys, base URLs) are intentionally excluded for security.
    """ # noqa: E501
    reflect_mission: Optional[StrictStr] = Field(default=None, description="Mission/context for Reflect operations")
    retain_mission: Optional[StrictStr] = Field(default=None, description="Steers what gets extracted during retain")
    retain_extraction_mode: Optional[StrictStr] = Field(default=None, description="Fact extraction mode: 'concise' (default), 'verbose', or 'custom'")
    retain_custom_instructions: Optional[StrictStr] = Field(default=None, description="Custom extraction prompt (when mode='custom')")
    retain_chunk_size: Optional[StrictInt] = Field(default=None, description="Max token size for each content chunk")
    enable_observations: Optional[StrictBool] = Field(default=None, description="Toggle observation consolidation")
    observations_mission: Optional[StrictStr] = Field(default=None, description="Controls what gets synthesised")
    disposition_skepticism: Optional[Annotated[int, Field(le=5, strict=True, ge=1)]] = Field(default=None, description="Skepticism trait (1-5)")
    disposition_literalism: Optional[Annotated[int, Field(le=5, strict=True, ge=1)]] = Field(default=None, description="Literalism trait (1-5)")
    disposition_empathy: Optional[Annotated[int, Field(le=5, strict=True, ge=1)]] = Field(default=None, description="Empathy trait (1-5)")
    entity_labels: Optional[List[Dict[str, Any]]] = Field(default=None, description="Controlled vocabulary for entity labels")
    entities_allow_free_form: Optional[StrictBool] = Field(default=None, description="Allow entities outside the label vocabulary")
    retain_default_strategy: Optional[StrictStr] = Field(default=None, description="Name of the default retain strategy (key into retain_strategies map)")
    retain_strategies: Optional[Dict[str, Any]] = Field(default=None, description="Map of retain strategy name to per-strategy config dict")
    retain_chunk_batch_size: Optional[StrictInt] = Field(default=None, description="Max chunks per streaming batch (0 disables batching)")
    mcp_enabled_tools: Optional[List[StrictStr]] = Field(default=None, description="MCP tool allowlist for this bank (None = all tools)")
    consolidation_llm_batch_size: Optional[StrictInt] = Field(default=None, description="LLM batch size for observation consolidation")
    consolidation_source_facts_max_tokens: Optional[StrictInt] = Field(default=None, description="Max tokens of source facts per consolidation batch")
    consolidation_source_facts_max_tokens_per_observation: Optional[StrictInt] = Field(default=None, description="Max tokens of source facts per observation")
    max_observations_per_scope: Optional[StrictInt] = Field(default=None, description="Max observations to retain per consolidation scope")
    reflect_source_facts_max_tokens: Optional[StrictInt] = Field(default=None, description="Max tokens of source facts per reflect call")
    llm_gemini_safety_settings: Optional[List[Any]] = Field(default=None, description="Per-bank Gemini/VertexAI safety filter settings")
    recall_budget_function: Optional[StrictStr] = Field(default=None, description="Recall budget mapping function: 'fixed' or 'adaptive'")
    recall_budget_fixed_low: Optional[StrictInt] = Field(default=None, description="Fixed thinking_budget for budget=low (function='fixed')")
    recall_budget_fixed_mid: Optional[StrictInt] = Field(default=None, description="Fixed thinking_budget for budget=mid (function='fixed')")
    recall_budget_fixed_high: Optional[StrictInt] = Field(default=None, description="Fixed thinking_budget for budget=high (function='fixed')")
    recall_budget_adaptive_low: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Ratio of max_tokens for budget=low (function='adaptive')")
    recall_budget_adaptive_mid: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Ratio of max_tokens for budget=mid (function='adaptive')")
    recall_budget_adaptive_high: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Ratio of max_tokens for budget=high (function='adaptive')")
    recall_budget_min: Optional[StrictInt] = Field(default=None, description="Floor for the adaptive function (after clamping)")
    recall_budget_max: Optional[StrictInt] = Field(default=None, description="Ceiling for the adaptive function (after clamping)")
    __properties: ClassVar[List[str]] = ["reflect_mission", "retain_mission", "retain_extraction_mode", "retain_custom_instructions", "retain_chunk_size", "enable_observations", "observations_mission", "disposition_skepticism", "disposition_literalism", "disposition_empathy", "entity_labels", "entities_allow_free_form", "retain_default_strategy", "retain_strategies", "retain_chunk_batch_size", "mcp_enabled_tools", "consolidation_llm_batch_size", "consolidation_source_facts_max_tokens", "consolidation_source_facts_max_tokens_per_observation", "max_observations_per_scope", "reflect_source_facts_max_tokens", "llm_gemini_safety_settings", "recall_budget_function", "recall_budget_fixed_low", "recall_budget_fixed_mid", "recall_budget_fixed_high", "recall_budget_adaptive_low", "recall_budget_adaptive_mid", "recall_budget_adaptive_high", "recall_budget_min", "recall_budget_max"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BankTemplateConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if reflect_mission (nullable) is None
        # and model_fields_set contains the field
        if self.reflect_mission is None and "reflect_mission" in self.model_fields_set:
            _dict['reflect_mission'] = None

        # set to None if retain_mission (nullable) is None
        # and model_fields_set contains the field
        if self.retain_mission is None and "retain_mission" in self.model_fields_set:
            _dict['retain_mission'] = None

        # set to None if retain_extraction_mode (nullable) is None
        # and model_fields_set contains the field
        if self.retain_extraction_mode is None and "retain_extraction_mode" in self.model_fields_set:
            _dict['retain_extraction_mode'] = None

        # set to None if retain_custom_instructions (nullable) is None
        # and model_fields_set contains the field
        if self.retain_custom_instructions is None and "retain_custom_instructions" in self.model_fields_set:
            _dict['retain_custom_instructions'] = None

        # set to None if retain_chunk_size (nullable) is None
        # and model_fields_set contains the field
        if self.retain_chunk_size is None and "retain_chunk_size" in self.model_fields_set:
            _dict['retain_chunk_size'] = None

        # set to None if enable_observations (nullable) is None
        # and model_fields_set contains the field
        if self.enable_observations is None and "enable_observations" in self.model_fields_set:
            _dict['enable_observations'] = None

        # set to None if observations_mission (nullable) is None
        # and model_fields_set contains the field
        if self.observations_mission is None and "observations_mission" in self.model_fields_set:
            _dict['observations_mission'] = None

        # set to None if disposition_skepticism (nullable) is None
        # and model_fields_set contains the field
        if self.disposition_skepticism is None and "disposition_skepticism" in self.model_fields_set:
            _dict['disposition_skepticism'] = None

        # set to None if disposition_literalism (nullable) is None
        # and model_fields_set contains the field
        if self.disposition_literalism is None and "disposition_literalism" in self.model_fields_set:
            _dict['disposition_literalism'] = None

        # set to None if disposition_empathy (nullable) is None
        # and model_fields_set contains the field
        if self.disposition_empathy is None and "disposition_empathy" in self.model_fields_set:
            _dict['disposition_empathy'] = None

        # set to None if entity_labels (nullable) is None
        # and model_fields_set contains the field
        if self.entity_labels is None and "entity_labels" in self.model_fields_set:
            _dict['entity_labels'] = None

        # set to None if entities_allow_free_form (nullable) is None
        # and model_fields_set contains the field
        if self.entities_allow_free_form is None and "entities_allow_free_form" in self.model_fields_set:
            _dict['entities_allow_free_form'] = None

        # set to None if retain_default_strategy (nullable) is None
        # and model_fields_set contains the field
        if self.retain_default_strategy is None and "retain_default_strategy" in self.model_fields_set:
            _dict['retain_default_strategy'] = None

        # set to None if retain_strategies (nullable) is None
        # and model_fields_set contains the field
        if self.retain_strategies is None and "retain_strategies" in self.model_fields_set:
            _dict['retain_strategies'] = None

        # set to None if retain_chunk_batch_size (nullable) is None
        # and model_fields_set contains the field
        if self.retain_chunk_batch_size is None and "retain_chunk_batch_size" in self.model_fields_set:
            _dict['retain_chunk_batch_size'] = None

        # set to None if mcp_enabled_tools (nullable) is None
        # and model_fields_set contains the field
        if self.mcp_enabled_tools is None and "mcp_enabled_tools" in self.model_fields_set:
            _dict['mcp_enabled_tools'] = None

        # set to None if consolidation_llm_batch_size (nullable) is None
        # and model_fields_set contains the field
        if self.consolidation_llm_batch_size is None and "consolidation_llm_batch_size" in self.model_fields_set:
            _dict['consolidation_llm_batch_size'] = None

        # set to None if consolidation_source_facts_max_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.consolidation_source_facts_max_tokens is None and "consolidation_source_facts_max_tokens" in self.model_fields_set:
            _dict['consolidation_source_facts_max_tokens'] = None

        # set to None if consolidation_source_facts_max_tokens_per_observation (nullable) is None
        # and model_fields_set contains the field
        if self.consolidation_source_facts_max_tokens_per_observation is None and "consolidation_source_facts_max_tokens_per_observation" in self.model_fields_set:
            _dict['consolidation_source_facts_max_tokens_per_observation'] = None

        # set to None if max_observations_per_scope (nullable) is None
        # and model_fields_set contains the field
        if self.max_observations_per_scope is None and "max_observations_per_scope" in self.model_fields_set:
            _dict['max_observations_per_scope'] = None

        # set to None if reflect_source_facts_max_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.reflect_source_facts_max_tokens is None and "reflect_source_facts_max_tokens" in self.model_fields_set:
            _dict['reflect_source_facts_max_tokens'] = None

        # set to None if llm_gemini_safety_settings (nullable) is None
        # and model_fields_set contains the field
        if self.llm_gemini_safety_settings is None and "llm_gemini_safety_settings" in self.model_fields_set:
            _dict['llm_gemini_safety_settings'] = None

        # set to None if recall_budget_function (nullable) is None
        # and model_fields_set contains the field
        if self.recall_budget_function is None and "recall_budget_function" in self.model_fields_set:
            _dict['recall_budget_function'] = None

        # set to None if recall_budget_fixed_low (nullable) is None
        # and model_fields_set contains the field
        if self.recall_budget_fixed_low is None and "recall_budget_fixed_low" in self.model_fields_set:
            _dict['recall_budget_fixed_low'] = None

        # set to None if recall_budget_fixed_mid (nullable) is None
        # and model_fields_set contains the field
        if self.recall_budget_fixed_mid is None and "recall_budget_fixed_mid" in self.model_fields_set:
            _dict['recall_budget_fixed_mid'] = None

        # set to None if recall_budget_fixed_high (nullable) is None
        # and model_fields_set contains the field
        if self.recall_budget_fixed_high is None and "recall_budget_fixed_high" in self.model_fields_set:
            _dict['recall_budget_fixed_high'] = None

        # set to None if recall_budget_adaptive_low (nullable) is None
        # and model_fields_set contains the field
        if self.recall_budget_adaptive_low is None and "recall_budget_adaptive_low" in self.model_fields_set:
            _dict['recall_budget_adaptive_low'] = None

        # set to None if recall_budget_adaptive_mid (nullable) is None
        # and model_fields_set contains the field
        if self.recall_budget_adaptive_mid is None and "recall_budget_adaptive_mid" in self.model_fields_set:
            _dict['recall_budget_adaptive_mid'] = None

        # set to None if recall_budget_adaptive_high (nullable) is None
        # and model_fields_set contains the field
        if self.recall_budget_adaptive_high is None and "recall_budget_adaptive_high" in self.model_fields_set:
            _dict['recall_budget_adaptive_high'] = None

        # set to None if recall_budget_min (nullable) is None
        # and model_fields_set contains the field
        if self.recall_budget_min is None and "recall_budget_min" in self.model_fields_set:
            _dict['recall_budget_min'] = None

        # set to None if recall_budget_max (nullable) is None
        # and model_fields_set contains the field
        if self.recall_budget_max is None and "recall_budget_max" in self.model_fields_set:
            _dict['recall_budget_max'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BankTemplateConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "reflect_mission": obj.get("reflect_mission"),
            "retain_mission": obj.get("retain_mission"),
            "retain_extraction_mode": obj.get("retain_extraction_mode"),
            "retain_custom_instructions": obj.get("retain_custom_instructions"),
            "retain_chunk_size": obj.get("retain_chunk_size"),
            "enable_observations": obj.get("enable_observations"),
            "observations_mission": obj.get("observations_mission"),
            "disposition_skepticism": obj.get("disposition_skepticism"),
            "disposition_literalism": obj.get("disposition_literalism"),
            "disposition_empathy": obj.get("disposition_empathy"),
            "entity_labels": obj.get("entity_labels"),
            "entities_allow_free_form": obj.get("entities_allow_free_form"),
            "retain_default_strategy": obj.get("retain_default_strategy"),
            "retain_strategies": obj.get("retain_strategies"),
            "retain_chunk_batch_size": obj.get("retain_chunk_batch_size"),
            "mcp_enabled_tools": obj.get("mcp_enabled_tools"),
            "consolidation_llm_batch_size": obj.get("consolidation_llm_batch_size"),
            "consolidation_source_facts_max_tokens": obj.get("consolidation_source_facts_max_tokens"),
            "consolidation_source_facts_max_tokens_per_observation": obj.get("consolidation_source_facts_max_tokens_per_observation"),
            "max_observations_per_scope": obj.get("max_observations_per_scope"),
            "reflect_source_facts_max_tokens": obj.get("reflect_source_facts_max_tokens"),
            "llm_gemini_safety_settings": obj.get("llm_gemini_safety_settings"),
            "recall_budget_function": obj.get("recall_budget_function"),
            "recall_budget_fixed_low": obj.get("recall_budget_fixed_low"),
            "recall_budget_fixed_mid": obj.get("recall_budget_fixed_mid"),
            "recall_budget_fixed_high": obj.get("recall_budget_fixed_high"),
            "recall_budget_adaptive_low": obj.get("recall_budget_adaptive_low"),
            "recall_budget_adaptive_mid": obj.get("recall_budget_adaptive_mid"),
            "recall_budget_adaptive_high": obj.get("recall_budget_adaptive_high"),
            "recall_budget_min": obj.get("recall_budget_min"),
            "recall_budget_max": obj.get("recall_budget_max")
        })
        return _obj


