# coding: utf-8

"""
    Entelechy HTTP API

    HTTP API for Entelechy

    The version of the OpenAPI document: 0.5.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from entelechy_client_api.models.mental_model_trigger_output_tag_groups_inner import MentalModelTriggerOutputTagGroupsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MentalModelTriggerOutput(BaseModel):
    """
    Trigger settings for a mental model.
    """ # noqa: E501
    mode: Optional[StrictStr] = Field(default='full', description="Refresh mode. 'full' (default) regenerates the mental model content from scratch on each refresh. 'delta' performs surgical edits against the existing content: unchanged sections are preserved byte-for-byte, stale content is removed, new content is added. If the mental model has no existing content, or if the source_query has changed since the last refresh, delta mode falls back to a full regeneration automatically.")
    refresh_after_consolidation: Optional[StrictBool] = Field(default=False, description="If true, refresh this mental model after observations consolidation (real-time mode)")
    fact_types: Optional[List[StrictStr]] = Field(default=None, description="Filter which fact types are retrieved during reflect. None means all types (world, experience, observation).")
    exclude_mental_models: Optional[StrictBool] = Field(default=False, description="If true, exclude all mental models from the reflect loop (skip search_mental_models tool).")
    exclude_mental_model_ids: Optional[List[StrictStr]] = Field(default=None, description="Exclude specific mental models by ID from the reflect loop.")
    tags_match: Optional[StrictStr] = Field(default=None, description="Override how the model's tags filter memories during refresh. If not set, defaults to 'all_strict' when the model has tags (security isolation) or 'any' when the model has no tags. Set to 'any' to include untagged memories alongside tagged ones during refresh.")
    tag_groups: Optional[List[MentalModelTriggerOutputTagGroupsInner]] = Field(default=None, description="Compound boolean tag expressions to use during refresh instead of the model's own tags. When set, these tag groups are passed to reflect and the model's flat tags are NOT used for filtering. Supports nested and/or/not expressions for complex tag-based scoping.")
    include_chunks: Optional[StrictBool] = Field(default=None, description="Override whether the internal recall used during refresh returns raw chunk text. None means use the bank/global config default (recall_include_chunks).")
    recall_max_tokens: Optional[StrictInt] = Field(default=None, description="Override the token budget for facts returned by the internal recall during refresh. None means use the bank/global config default (recall_max_tokens).")
    recall_chunks_max_tokens: Optional[StrictInt] = Field(default=None, description="Override the token budget for raw chunks returned by the internal recall during refresh. None means use the bank/global config default (recall_chunks_max_tokens).")
    __properties: ClassVar[List[str]] = ["mode", "refresh_after_consolidation", "fact_types", "exclude_mental_models", "exclude_mental_model_ids", "tags_match", "tag_groups", "include_chunks", "recall_max_tokens", "recall_chunks_max_tokens"]

    @field_validator('mode')
    def mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['full', 'delta']):
            raise ValueError("must be one of enum values ('full', 'delta')")
        return value

    @field_validator('fact_types')
    def fact_types_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        for i in value:
            if i not in set(['world', 'experience', 'observation']):
                raise ValueError("each list item must be one of ('world', 'experience', 'observation')")
        return value

    @field_validator('tags_match')
    def tags_match_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['any', 'all', 'any_strict', 'all_strict']):
            raise ValueError("must be one of enum values ('any', 'all', 'any_strict', 'all_strict')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MentalModelTriggerOutput from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in tag_groups (list)
        _items = []
        if self.tag_groups:
            for _item_tag_groups in self.tag_groups:
                _items.append(_item_tag_groups.to_dict() if _item_tag_groups is not None else None)
            _dict['tag_groups'] = _items
        # set to None if fact_types (nullable) is None
        # and model_fields_set contains the field
        if self.fact_types is None and "fact_types" in self.model_fields_set:
            _dict['fact_types'] = None

        # set to None if exclude_mental_model_ids (nullable) is None
        # and model_fields_set contains the field
        if self.exclude_mental_model_ids is None and "exclude_mental_model_ids" in self.model_fields_set:
            _dict['exclude_mental_model_ids'] = None

        # set to None if tags_match (nullable) is None
        # and model_fields_set contains the field
        if self.tags_match is None and "tags_match" in self.model_fields_set:
            _dict['tags_match'] = None

        # set to None if tag_groups (nullable) is None
        # and model_fields_set contains the field
        if self.tag_groups is None and "tag_groups" in self.model_fields_set:
            _dict['tag_groups'] = None

        # set to None if include_chunks (nullable) is None
        # and model_fields_set contains the field
        if self.include_chunks is None and "include_chunks" in self.model_fields_set:
            _dict['include_chunks'] = None

        # set to None if recall_max_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.recall_max_tokens is None and "recall_max_tokens" in self.model_fields_set:
            _dict['recall_max_tokens'] = None

        # set to None if recall_chunks_max_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.recall_chunks_max_tokens is None and "recall_chunks_max_tokens" in self.model_fields_set:
            _dict['recall_chunks_max_tokens'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MentalModelTriggerOutput from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "mode": obj.get("mode") if obj.get("mode") is not None else 'full',
            "refresh_after_consolidation": obj.get("refresh_after_consolidation") if obj.get("refresh_after_consolidation") is not None else False,
            "fact_types": obj.get("fact_types"),
            "exclude_mental_models": obj.get("exclude_mental_models") if obj.get("exclude_mental_models") is not None else False,
            "exclude_mental_model_ids": obj.get("exclude_mental_model_ids"),
            "tags_match": obj.get("tags_match"),
            "tag_groups": [MentalModelTriggerOutputTagGroupsInner.from_dict(_item) for _item in obj["tag_groups"]] if obj.get("tag_groups") is not None else None,
            "include_chunks": obj.get("include_chunks"),
            "recall_max_tokens": obj.get("recall_max_tokens"),
            "recall_chunks_max_tokens": obj.get("recall_chunks_max_tokens")
        })
        return _obj


