# coding: utf-8

"""
    Entelechy HTTP API

    HTTP API for Entelechy

    The version of the OpenAPI document: 0.5.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from entelechy_client_api.models.chunk_data import ChunkData
from entelechy_client_api.models.entity_state_response import EntityStateResponse
from entelechy_client_api.models.recall_result import RecallResult
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class RecallResponse(BaseModel):
    """
    Response model for recall endpoints.
    """ # noqa: E501
    results: List[RecallResult]
    trace: Optional[Dict[str, Any]] = None
    entities: Optional[Dict[str, EntityStateResponse]] = Field(default=None, description="Entity states for entities mentioned in results")
    chunks: Optional[Dict[str, ChunkData]] = Field(default=None, description="Chunks for facts, keyed by chunk_id")
    source_facts: Optional[Dict[str, RecallResult]] = Field(default=None, description="Source facts for observation-type results, keyed by fact ID")
    __properties: ClassVar[List[str]] = ["results", "trace", "entities", "chunks", "source_facts"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RecallResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in results (list)
        _items = []
        if self.results:
            for _item_results in self.results:
                _items.append(_item_results.to_dict() if _item_results is not None else None)
            _dict['results'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in entities (dict)
        _field_dict = {}
        if self.entities:
            for _key_entities in self.entities:
                _field_dict[_key_entities] = self.entities[_key_entities].to_dict() if self.entities[_key_entities] is not None else None
            _dict['entities'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in chunks (dict)
        _field_dict = {}
        if self.chunks:
            for _key_chunks in self.chunks:
                _field_dict[_key_chunks] = self.chunks[_key_chunks].to_dict() if self.chunks[_key_chunks] is not None else None
            _dict['chunks'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each value in source_facts (dict)
        _field_dict = {}
        if self.source_facts:
            for _key_source_facts in self.source_facts:
                _field_dict[_key_source_facts] = self.source_facts[_key_source_facts].to_dict() if self.source_facts[_key_source_facts] is not None else None
            _dict['source_facts'] = _field_dict
        # set to None if trace (nullable) is None
        # and model_fields_set contains the field
        if self.trace is None and "trace" in self.model_fields_set:
            _dict['trace'] = None

        # set to None if entities (nullable) is None
        # and model_fields_set contains the field
        if self.entities is None and "entities" in self.model_fields_set:
            _dict['entities'] = None

        # set to None if chunks (nullable) is None
        # and model_fields_set contains the field
        if self.chunks is None and "chunks" in self.model_fields_set:
            _dict['chunks'] = None

        # set to None if source_facts (nullable) is None
        # and model_fields_set contains the field
        if self.source_facts is None and "source_facts" in self.model_fields_set:
            _dict['source_facts'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RecallResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "results": [RecallResult.from_dict(_item) for _item in obj["results"]] if obj.get("results") is not None else None,
            "trace": obj.get("trace"),
            "entities": dict(
                (_k, EntityStateResponse.from_dict(_v))
                for _k, _v in obj["entities"].items()
            )
            if obj.get("entities") is not None
            else None,
            "chunks": dict(
                (_k, ChunkData.from_dict(_v))
                for _k, _v in obj["chunks"].items()
            )
            if obj.get("chunks") is not None
            else None,
            "source_facts": dict(
                (_k, RecallResult.from_dict(_v))
                for _k, _v in obj["source_facts"].items()
            )
            if obj.get("source_facts") is not None
            else None
        })
        return _obj


